server:
  port: 6060

spring:
  datasource:
    type:
    driver-class-name:
    url:
    username:
    password:
    hikari:
      pool-name:
      connection-timeout:
      minimum-idle:
      maximum-pool-size:
      auto-commit:
      idle-timeout:
      max-lifetime:
      connection-test-query: