spring:
  application:
    name: stock-monitor-web
  profiles:
    active: dev
logging:
  level:
    root: info

mybatis-plus:
  global-config:
    db-config:
      id-type:
      update-strategy: not_empty
  mapper-locations: classpath*:/mappers/*.xml